// Common disposable / throwaway email domains
const DISPOSABLE_DOMAINS = new Set([
  '10minutemail.com', '10minutemail.net', '10minutemail.org',
  'guerrillamail.com', 'guerrillamail.net', 'guerrillamail.org',
  'guerrillamail.biz', 'guerrillamail.de', 'guerrillamail.info',
  'mailinator.com', 'mailinator.net', 'mailinator.org',
  'throwam.com', 'throwaway.email', 'trashmail.com',
  'trashmail.me', 'trashmail.net', 'trashmail.org',
  'yopmail.com', 'yopmail.fr', 'yopmail.net',
  'tempmail.com', 'tempmail.net', 'temp-mail.org',
  'temp-mail.io', 'tempinbox.com', 'tempr.email',
  'fakeinbox.com', 'fake-box.com', 'fakemail.fr',
  'mailnull.com', 'mailnull.net', 'spamgourmet.com',
  'spamgourmet.net', 'spamgourmet.org',
  'maildrop.cc', 'sharklasers.com', 'guerrillamailblock.com',
  'grr.la', 'spam4.me', 'dispostable.com',
  'mintemail.com', 'nospamfor.us', 'discard.email',
  'cuvox.de', 'dayrep.com', 'einrot.com',
  'fleckens.hu', 'gustr.com', 'harakirimail.com',
  'hulapla.de', 'incognitomail.org', 'jetable.fr.nf',
  'jourrapide.com', 'kurzepost.de', 'letthemeatspam.com',
  'lhsdv.com', 'mailexpire.com', 'mt2009.com',
  'mvrht.com', 'meltmail.com', 'nwldx.com',
  'objectmail.com', 'obobbo.com', 'pookmail.com',
  'proxymail.eu', 'rcpt.at', 'recode.me',
  'regbypass.com', 'safetymail.info', 'sendspamhere.com',
  'shiftmail.com', 'smellfear.com', 'sneakemail.com',
  'sogetthis.com', 'soodonims.com', 'spamfree24.org',
  'spamgob.com', 'spamherelots.com', 'spamhereplease.com',
  'spamthisplease.com', 'spaml.de', 'supergreatmail.com',
  'teleworm.us', 'thisisnotmyrealemail.com', 'tilien.com',
  'uroid.com', 'veryrealemail.com', 'viditag.com',
  'wetrainbayarea.org', 'wh4f.org', 'whyspam.me',
  'willhackforfood.biz', 'wuzupmail.net', 'xagloo.com',
  'xemaps.com', 'xents.com', 'xmaily.com',
  'xoxy.net', 'yep.it', 'z1p.biz',
  'za.com', 'zehnminuten.de', 'zehnminutenmail.de',
  'zippymail.info', 'zoemail.org', 'zxcv.com',
  'cock.li', 'airmail.cc', 'getairmail.com',
  'binkmail.com', 'bobmail.info', 'dropmail.me',
  'emailfake.com', 'emailondeck.com', 'emkei.cz',
  'epeius.tk', 'filzmail.com', 'fizmail.com',
  'freemail.ms', 'fuckingduh.com', 'gowikibooks.com',
  'gowikicampus.com', 'gowikicars.com', 'gowikifilms.com',
  'gowikigames.com', 'gowikimusic.com', 'gowikinetwork.com',
  'gowikitravel.com', 'gowikitv.com', 'h8s.org',
  'hatespam.org', 'inoutmail.eu', 'inoutmail.info',
  'inoutmail.net', 'inoutmail.de',
])

export function isDisposableEmail(email: string): boolean {
  const domain = email.split('@')[1]?.toLowerCase()
  if (!domain) return false
  return DISPOSABLE_DOMAINS.has(domain)
}
