import { Link } from 'react-router-dom'

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section style={{ marginBottom: 36 }}>
      <h2 style={{ fontSize: 17, fontWeight: 600, color: '#111827', marginBottom: 12 }}>{title}</h2>
      <div style={{ fontSize: 14, color: '#374151', lineHeight: 1.75 }}>{children}</div>
    </section>
  )
}

export function PrivacyEn() {
  return (
    <div style={{ minHeight: '100vh', background: '#ffffff', fontFamily: 'inherit' }}>
      <header style={{
        borderBottom: '1px solid #e5e7eb', padding: '0 32px', height: 56,
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        background: '#ffffff',
      }}>
        <Link to="/en" style={{ display: 'flex', alignItems: 'center', gap: 8, textDecoration: 'none' }}>
          <svg width={28} height={28} viewBox="0 0 28 28" fill="none">
            <rect width="28" height="28" rx="7" fill="#1a56db" />
            <path d="M8 10h12M8 14h8M8 18h10" stroke="#fff" strokeWidth="2" strokeLinecap="round"/>
          </svg>
          <span style={{ fontSize: 18, fontWeight: 700, color: '#111827' }}>AnonDoc</span>
        </Link>
        <Link to="/en" style={{ fontSize: 13, color: '#6b7280', textDecoration: 'none' }}>← Back</Link>
      </header>

      <main style={{ maxWidth: 720, margin: '0 auto', padding: '48px 32px 80px' }}>
        <h1 style={{ fontSize: 28, fontWeight: 800, color: '#111827', marginBottom: 8 }}>
          Privacy Policy
        </h1>
        <p style={{ fontSize: 13, color: '#9ca3af', marginBottom: 40 }}>Last Updated: April 2026</p>

        <Section title="1. Summary: Zero-Knowledge Architecture">
          <p>
            AnonDoc is designed to never see your data. Document processing (anonymization, parsing,
            tokenization) occurs 100% locally in your browser using Web Workers. No document content,
            text, or metadata is ever sent to our servers, logged, or shared with third parties.
          </p>
        </Section>

        <Section title="2. Information We Collect">
          <p>We only collect data strictly necessary for account management:</p>
          <ul style={{ paddingLeft: 20, marginTop: 8 }}>
            <li style={{ marginBottom: 6 }}>
              <strong>Account information:</strong> Email address and password hash (stored encrypted
              using bcrypt) for login and subscription management.
            </li>
            <li style={{ marginBottom: 6 }}>
              <strong>Business inquiry data:</strong> If you submit a business contact form, we collect
              the data you provide (company name, role, country, industry, expected volume, email,
              message) to respond to your inquiry.
            </li>
            <li style={{ marginBottom: 6 }}>
              <strong>Payment data:</strong> AnonDoc currently does not process payments. When paid
              plans launch, payment processing will be handled by Stripe and this Privacy Policy will
              be updated accordingly before any payment processing begins.
            </li>
            <li>
              <strong>No tracking:</strong> AnonDoc does not use tracking cookies, Google Analytics,
              fingerprinting, or any third-party analytics tools.
            </li>
          </ul>
        </Section>

        <Section title="3. Email Service">
          <p>
            Transactional emails (account verification, business inquiry replies, Pro waitlist
            confirmations) are sent via <strong>Resend</strong> (resend.com), operating from EU
            region (Ireland). Resend processes only the email address and message content needed to
            deliver the email.
          </p>
        </Section>

        <Section title="4. Local Data & Document Keys">
          <p>
            Anonymization session history and Document Keys (.key files) generated by the app are
            stored exclusively in your device's local storage (IndexedDB), encrypted with AES-256-GCM.
          </p>
          <p style={{ marginTop: 8 }}>
            <strong>You are in full control:</strong> clearing your browser cache permanently deletes
            all local history and keys. We cannot recover them.
          </p>
        </Section>

        <Section title="5. Document Keys & Security">
          <p>
            When you download a Document Key (.key), it is generated locally on your device. AnonDoc
            servers never receive a copy. Without this key, mathematical restoration of original data
            is impossible. Please keep it safe — we cannot restore it for you.
          </p>
        </Section>

        <Section title="6. Your Rights (GDPR)">
          <p>
            Under the GDPR, you have the right to access, rectify, erase, restrict, and port your
            personal data, and to object to processing.
          </p>
          <ul style={{ paddingLeft: 20, marginTop: 8 }}>
            <li style={{ marginBottom: 6 }}>
              To exercise rights regarding <strong>account data</strong> (email): Contact us at{' '}
              <a href="mailto:dpo@anondoc.app" style={{ color: '#1a56db' }}>dpo@anondoc.app</a>
            </li>
            <li style={{ marginBottom: 6 }}>
              To erase <strong>local document data</strong>: Clear your browser's site storage for
              anondoc.app
            </li>
            <li>
              You have the right to lodge a complaint with your national data protection authority.
            </li>
          </ul>
        </Section>

        <Section title="7. Data Retention">
          <ul style={{ paddingLeft: 20, marginTop: 8 }}>
            <li style={{ marginBottom: 6 }}>
              <strong>Account data:</strong> kept while your account is active. Upon account deletion,
              removed within 30 days from production database and within 90 days from backups.
            </li>
            <li style={{ marginBottom: 6 }}>
              <strong>Business inquiry data:</strong> kept for up to 24 months for follow-up
              purposes, then deleted.
            </li>
            <li>
              <strong>Local browser data:</strong> controlled entirely by you.
            </li>
          </ul>
        </Section>

        <Section title="8. Changes to This Policy">
          <p>
            We will notify users by email of any material changes to this Privacy Policy.
            Last updated: April 2026.
          </p>
        </Section>

        <Section title="9. Contact">
          <p>
            For privacy inquiries:{' '}
            <a href="mailto:dpo@anondoc.app" style={{ color: '#1a56db' }}>dpo@anondoc.app</a>
          </p>
        </Section>
      </main>

      <footer style={{
        padding: '24px 32px', borderTop: '1px solid #e5e7eb',
        textAlign: 'center', fontSize: 12, color: '#9ca3af',
      }}>
        <Link to="/en" style={{ color: '#9ca3af', textDecoration: 'underline' }}>AnonDoc</Link>
        {' · '}
        <a href="mailto:dpo@anondoc.app" style={{ color: '#9ca3af', textDecoration: 'underline' }}>
          dpo@anondoc.app
        </a>
      </footer>
    </div>
  )
}
